### PR TITLE
update the root-conda docker version to latest version

### PR DESCRIPTION
**Pull request by amanmdesai**
Hi @klieret  As discussed in #12 we need to upgrade the root docker version. Currently the recommended version is 6.18, which is no longer available.

### CODE REVIEW

**Comment by amanmdesai** [comment]
I have also updated the test-analysis.yml. It will now run the analysis with rootproject/root:6.26.10-conda container

**Review by klieret — APPROVED** [review]
Thanks a lot, this looks good to me

**Comment by klieret** [comment]
Btw, perhaps we should also add a monthly run to the CI (so we know it fails if the version goes out of date): like here or so https://jasonet.co/posts/scheduled-actions/

**Comment by amanmdesai** [comment]
Thats a nice idea. I will implement that.

**Pull request merged**
